wandb_version: 1

_wandb:
  desc: null
  value:
    m: []
    cli_version: 0.22.2
    python_version: 3.12.3
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 51
      - 53
      - 105
      2:
      - 1
      - 5
      - 41
      - 49
      - 51
      - 53
      - 105
      3:
      - 4
      - 13
      - 16
      - 17
      - 37
      - 42
      4: 3.12.3
      5: 0.22.2
      8:
      - 1
      - 2
      13: linux-x86_64
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1760370489
    e:
      3mq6wdnhenbcuv4x5lkiptniow4z09tm:
        os: Linux-6.14.0-33-generic-x86_64-with-glibc2.39
        python: CPython 3.12.3
        started_at: '2025-10-13T15:48:09.426732Z'
        program: /home/chakri/Documents/S-7/MLoPs/Mlops2025w-112201022/Assignments/Assigment-5/Q1_conll2003_stats.ipynb
        code_path: Assignments/Assigment-5/Q1_conll2003_stats.ipynb
        code_path_local: Q1_conll2003_stats.ipynb
        git:
          remote_url: git@github.com:ChakradharReddy3237/Mlops2025w-112201022.git
          commit: 140604414ac47d2b71c6e2fb809097f711f47c9c
        root: /home/chakri/Documents/S-7/MLoPs/Mlops2025w-112201022/Assignments/Assigment-5
        host: dell
        executable: /home/chakri/Documents/Projects/Chicken-Disease-Classification/chicken/bin/python
        cpu_count: 14
        cpu_count_logical: 20
        gpu_type: NVIDIA GeForce RTX 3050 Laptop GPU
        gpu_count: 1
        disk:
          /:
            total: '231931916288'
            used: '193351233536'
        memory:
          total: '16436441088'
        gpu_nvidia:
        - name: NVIDIA GeForce RTX 3050 Laptop GPU
          memory_total: '4294967296'
          cuda_cores: 2048
          architecture: Ampere
          uuid: GPU-54341311-7b04-d6fc-2081-63860b058fb3
        cuda_version: '12.2'
        writer_id: 3mq6wdnhenbcuv4x5lkiptniow4z09tm
order:
  desc: null
  value: A
sequence:
  desc: null
  value:
  - cifar100
  - cifar10
